export const APPLICATION_TOKENS = {
  ANALYTICS_REPOSITORY: Symbol('ANALYTICS_REPOSITORY'),
  ASSIGNMENT_ALGORITHM: Symbol('ASSIGNMENT_ALGORITHM'),
  DELIVERY_PERSON_REPOSITORY: Symbol('DELIVERY_PERSON_REPOSITORY'),
  ORDER_REPOSITORY: Symbol('ORDER_REPOSITORY'),
  PASSWORD_HASHER: Symbol('PASSWORD_HASHER'),
  PRODUCT_REPOSITORY: Symbol('PRODUCT_REPOSITORY'),
  REFRESH_SESSION_REPOSITORY: Symbol('REFRESH_SESSION_REPOSITORY'),
  TOKEN_SERVICE: Symbol('TOKEN_SERVICE'),
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
} as const;
